local Constants = {
	-- Coins
	COIN_TAG = "Coin",
	COIN_PICKUP_SOUND_PITCH_INCREASE = 0.05,
	COIN_PICKUP_SOUND_PITCH_RESET_TIME = 1,
	COIN_PICKUP_TRANSPARENCY = 0.8,
	-- Moving platforms
	MOVING_PLATFORM_TAG = "MovingPlatform",
	MOVING_PLATFORM_SPEED_ATTRIBUTE = "speed",
	MOVING_PLATFORM_ANGULAR_SPEED_ATTRIBUTE = "angularSpeed",
	MOVING_PLATFORM_DELAY_ATTRIBUTE = "delay",
	MOVING_PLATFORM_RESPONSIVENESS = 50,
	-- One way platforms
	CHARACTER_GROUP = "Character",
	LOCAL_CHARACTER_GROUP = "LocalCharacter",
	ONE_WAY_PLATFORM_TAG = "OneWayPlatform",
	ONE_WAY_PLATFORM_GROUP = "OneWayPlatform",
	ONE_WAY_PLATFORM_UPDATE_RATE = 30,
	ONE_WAY_PLATFORM_UPDATE_DISTANCE = 100,
}

return Constants
